---
title: List clients
name: List-clients
collection: molecules
notes: |
  You can use either `<a class="client">` or `<div class="client">` for the list items.
---
<div class="list-clients">
  <div class="client">
    <img class="img-responsive" alt="Canton de Genève" src="{{data.path}}build/svg/canton-de-geneve.svg">
  </div>
  <a class="client" href="#">
    <img class="img-responsive" alt="Canton de Vaud" src="{{data.path}}build/svg/canton-de-vaud.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Confédération Suisse" src="{{data.path}}build/svg/confederation-suisse.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Ville de Genève" src="{{data.path}}build/svg/Ville-de-Geneve.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Cardis Sothebys" src="{{data.path}}build/svg/Cardis-Sothebys.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="RTS" src="{{data.path}}build/svg/RTS.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Le Temps" src="{{data.path}}build/svg/Le-Temps.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Vaudoise" src="{{data.path}}build/svg/Vaudoise.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="AXS" src="{{data.path}}build/svg/AXA.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="EHL" src="{{data.path}}build/svg/EHL.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Loterie Romande" src="{{data.path}}build/svg/Loterie-Romande.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Médecins sans Frontières" src="{{data.path}}build/svg/Medecins-sans-Frontieres.svg">
  </a>
  <a class="client" href="#">
    <img class="img-responsive" alt="Orbium" src="{{data.path}}build/svg/Orbium.svg">
  </a>
  <div class="client">
    <img class="img-responsive" alt="United World Wrestling" src="{{data.path}}build/svg/UWW.svg">
  </div>
</div>
