---
title: nav-access
name: Nav-access
collection: molecules
notes: |
  This navigation is hidden for the user and will be the first thing shown if he navigate through the keyboard.
---

<nav class="nav-access">
  <ul>
    <li><a class="btn btn-primary" href="/" accesskey="1">Page d'accueil du site Antistatique.net</a></li>
    <li><a class="btn btn-primary" href="#main-content" accesskey="2" >Passer la navigation</a></li>
    <li><a class="btn btn-primary" href="#full-accessible-navigation" accesskey="3" >Accéder à la navigation</a></li>
    <li><a class="btn btn-primary" href="mailto:info@antistatique.net" accesskey="9">Contacter Antistatique</a></li>
  </ul>
</nav>
