---
title: Product Card
name: product-card
collection: molecules
---
<div class="product-cards">
  <div class="product-card text-center text-thin">
    <p>Démonstration</p>
    <h3>Gratuite</h3>
    <p>Bilan visibilité Google</p>
    <p>Présentation Street View Trusted</p>
    <p>Les Formules (tarifs)</p>
    <p>Détails prestations</p>
    <div class="spacer spacer-md"></div>
    <a href="#" class="btn btn-primary">Choisir</a>
  </div>
  <div class="product-card text-center text-thin">
    <p>Démonstration</p>
    <h3>Gratuite</h3>
    <p>Bilan visibilité Google</p>
    <p>Présentation Street View Trusted</p>
    <p>Les Formules (tarifs)</p>
    <p>Détails prestations</p>
    <div class="spacer spacer-md"></div>
    <a href="#" class="btn btn-primary">Choisir</a>
  </div>
  <div class="product-card text-center text-thin">
    <p>Démonstration</p>
    <h3>Gratuite</h3>
    <p>Bilan visibilité Google</p>
    <p>Présentation Street View Trusted</p>
    <p>Les Formules (tarifs)</p>
    <p>Détails prestations</p>
    <div class="spacer spacer-md"></div>
    <a href="#" class="btn btn-primary">Choisir</a>
  </div>
</div>
