---
title: Product Card
name: product-card
collection: molecules
---
<div class="product-cards">
  <div class="product-card text-center text-thin">
    <p>Démonstration</p>
    <h3>Gratuite</h3>
    <p>Bilan visibilité Google</p>
    <p>Présentation Street View Trusted</p>
    <p>Les Formules (tarifs)</p>
    <p>Détails prestations</p>
    <div class="spacer spacer-md"></div>
    <a href="mailto:hello@antistatique.net?subject=Je suis intéressé par une démonstration gratuite" class="btn btn-primary">Choisir</a>
  </div>
  <div class="product-card text-center text-thin">
    <p>Visite Virtuelle<br>360° Google</p>
    <h3><small>dès</small> 450 <small>CHF</small></h3>
    <p>Création, mise à jour Page G+</p>
    <p>Déplacement et Prise de vue</p>
    <p>4 points panoramiques</p>
    <div class="spacer spacer-md"></div>
    <a href="mailto:hello@antistatique.net?subject=Je suis intéressé par une visite virtuelle pour seulement CHF450" class="btn btn-primary">Choisir</a>
  </div>
  <div class="product-card text-center text-thin">
    <p>Page Google+</p>
    <h3>50 <small>CHF/page</small></h3>
    <p>Collecte et vérification des informations</p>
    <p>Localisation géographique</p>
    <p>Coordonnées et horaires d'ouverture</p>
    <div class="spacer spacer-md"></div>
    <a href="mailto:hello@antistatique.net?subject=Je suis intéressé par une visite virtuelle pour seulement CHF450" class="btn btn-primary">Choisir</a>
  </div>
</div>
