---
title: Services
name: services
collection: molecules
notes: |
  Component used to list services
---
<div class="services">
	<div class="triangle">
		<a href="#" class="h5 link-inverse triangle-link triangle-link-strategy">Strategie</a>
		<a href="#" class="h5 link-inverse triangle-link triangle-link-design">Design</a>
		<a href="#" class="h5 link-inverse triangle-link triangle-link-technology">Technology</a>
	</div>
</div>
