<?php

/**
 * Implements hook_migrate_api().
 */
function antistatique_migrate_migrate_api() {
  $api = array(
//    'api' => 2,
//    'groups' => array(
//      'drupal8' => array(
//        'title' => t('D8 Articles Migrations'),
//      ),
//    ),
//    'migrations' => array(
//      'D8User' => array(
//        'class_name' => 'MigrateD8UserMigration',
//        'group_name' => 'drupal8',
//      ),
//      'D8Article' => array(
//        'class_name' => 'MigrateD8ArticleMigration',
//        'group_name' => 'drupal8',
//      ),
//    ),
  );

  return $api;
}